package de.bbq.hangman.model;

import java.util.Arrays;
import java.util.List;
import java.util.Random;

/**
 * Provides words for the Hangman game.
 * Contains both predefined words and methods to get random words.
 *
 * @author Christos Poulios
 * @version 1.0
 */
public class WordProvider {
    /** List of predefined words for the game */
    private static final List<String> PREDEFINED_WORDS = Arrays.asList(
            "Haus",
            "Baum",
            "Auto",
            "Tisch",
            "Buch",
            "Katze",
            "Hund",
            "Maus",
            "Ball",
            "Stuhl",
            "Fenster",
            "Garten",
            "Schule",
            "Bleistift",
            "Telefon",
            "Computer",
            "Zeitung",
            "Kühlschrank",
            "Schlüssel",
            "Brille",
            "Fahrrad",
            "Apfel",
            "Banane",
            "Schokolade",
            "Kaffee",
            "Wasser",
            "Bäckerei",
            "Bibliothek",
            "Restaurant",
            "Krankenhaus",
            "Universität",
            "Spielplatz",
            "Supermarkt",
            "Briefkasten",
            "Zahnbürste",
            "Regenschirm",
            "Handtuch",
            "Fernseher",
            "Kalender",
            "Werkzeug",
            "Flugzeug",
            "Eisenbahn",
            "Motorrad",
            "Zeitschrift",
            "Tastatur",
            "Drucker",
            "Bildschirm",
            "Lautsprecher",
            "Mikrofon",
            "Kamera",
            "Staubsauger",
            "Waschmaschine",
            "Geschirrspüler",
            "Mikrowelle",
            "Toaster",
            "Kaffeemaschine",
            "Wasserkocher",
            "Backofen",
            "Spülbecken",
            "Schreibtisch",
            "Bücherregal",
            "Kleiderschrank",
            "Wörterbuch",
            "Taschenrechner",
            "Kugelschreiber",
            "Radiergummi",
            "Lineal",
            "Schere",
            "Klebstoff",
            "Heftklammer",
            "Briefumschlag",
            "Postkarte",
            "Briefmarke",
            "Kaleidoskop",
            "Mikroskop",
            "Teleskop",
            "Thermometer",
            "Barometer",
            "Kompass",
            "Stethoskop",
            "Röntgengerät",
            "Mikrochip",
            "Prozessor",
            "Algorithmus",
            "Datenbank",
            "Netzwerk",
            "Programmierung",
            "Entwicklung",
            "Forschung",
            "Wissenschaft",
            "Philosophie",
            "Psychologie",
            "Mathematik",
            "Geometrie",
            "Trigonometrie",
            "Quantenphysik",
            "Relativitätstheorie",
            "Photosynthese",
            "Metamorphose",
            "Chromosom",
            "Desoxyribonukleinsäure",
            "Mitochondrien",
            "Paradigmenwechsel",
            "Prokrastination",
            "Authentizität",
            "Ambivalenz",
            "Empathie",
            "Nostalgie",
            "Melancholie",
            "Euphorie",
            "Synchronizität",
            "Parallelität",
            "Kausalität",
            "Determination",
            "Transzendenz",
            "Metaphysik",
            "Epistemologie",
            "Ontologie",
            "Phänomenologie",
            "Hermeneutik",
            "Dialektik",
            "Syllogismus",
            "Tautologie",
            "Paradoxon",
            "Axiom",
            "Theorem",
            "Hypothese",
            "Synthese",
            "Analyse",
            "Interpretation",
            "Evaluation",
            "Koordination",
            "Integration",
            "Differenzierung",
            "Systematisierung",
            "Kategorisierung",
            "Klassifizierung",
            "Strukturierung",
            "Organisation",
            "Kommunikation",
            "Interaktion",
            "Kooperation",
            "Kollaboration",
            "Synergie",
            "Innovation",
            "Kreativität",
            "Inspiration",
            "Motivation",
            "Determination",
            "Persistenz",
            "Resilienz",
            "Authentizität",
            "Integrität",
            "Diversität",
            "Komplexität",
            "Flexibilität",
            "Adaptabilität",
            "Nachhaltigkeit",
            "Verantwortung",
            "Gerechtigkeit",
            "Demokratie",
            "Solidarität",
            "Gesellschaft",
            "Zivilisation",
            "Anthropologie",
            "Soziologie",
            "Ökologie",
            "Technologie",
            "Digitalisierung",
            "Globalisierung",
            "Transformation",
            "Revolution",
            "Evolution"
    );

    /** Random number generator */
    private final Random random;

    /**
     * Constructs a new WordProvider with a random number generator.
     */
    public WordProvider() {
        this.random = new Random();
    }

    /**
     * Gets a random word from the predefined list.
     *
     * @return A randomly selected word
     */
    public String getRandomWord() {
        int index = random.nextInt(PREDEFINED_WORDS.size());
        return PREDEFINED_WORDS.get(index);
    }
}
